# permissions for end users to edit helmlesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helmless-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helmlessoperator
    app.kubernetes.io/part-of: helmlessoperator
    app.kubernetes.io/managed-by: kustomize
  name: helmless-editor-role
rules:
- apiGroups:
  - helmless.redrvum.cloud
  resources:
  - helmlesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helmless.redrvum.cloud
  resources:
  - helmlesses/status
  verbs:
  - get
